name: RSOLV AutoFix

on:
  issues:
    types: [opened, labeled]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to fix'
        required: true
        type: string

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: RSOLV AutoFix
        uses: RSOLV-dev/rsolv-action@v2.5.2
        with:
          api_key: ${{ secrets.RSOLV_API_KEY }}
          issue_number: ${{ inputs.issue_number || github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}