name: RSOLV Security Automation

on:
  # Weekly security scan
  schedule:
    - cron: '0 0 * * 1'
  
  # Manual trigger for demo
  workflow_dispatch:
  
  # Autofix when issue is labeled or commented on
  issues:
    types: [labeled]
  issue_comment:
    types: [created]

permissions:
  issues: write
  contents: read
  pull-requests: write

jobs:
  security-scan:
    if: github.event_name != 'issues'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: RSOLV Security Scan
        uses: RSOLV-dev/rsolv-action@v2.1.3
        with:
          api_key: ${{ secrets.RSOLV_API_KEY }}
          scan_mode: scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RSOLV_API_URL: https://api.rsolv-staging.com
          RSOLV_DEBUG: 'true'  # Enable verbose logging to debug Claude responses

  autofix:
    if: |
      (github.event_name == 'issues' && github.event.label.name == 'rsolv:automate') ||
      (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '@rsolv-action'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for git operations
      
      - name: RSOLV AutoFix
        uses: RSOLV-dev/rsolv-action@v2.1.3
        with:
          api_key: ${{ secrets.RSOLV_API_KEY }}
          issue_number: ${{ github.event.issue.number }}
          scan_mode: fix  # Explicitly set to fix mode
          use_git_based_editing: 'true'  # Use git-based editing as per ADR-012
          max_issues: '1'  # Process only the triggered issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RSOLV_API_URL: https://api.rsolv-staging.com
          RSOLV_DEBUG: 'true'  # Enable verbose logging to debug Claude responses